// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trackin.Infrastructure.Context;

#nullable disable

namespace Trackin.Infrastructure.Migrations
{
    [DbContext(typeof(TrackinContext))]
    [Migration("20250907051051_v2-sqlServer")]
    partial class v2sqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trackin.Domain.Entity.Camera", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<double>("AnguloVisao")
                        .HasColumnType("float");

                    b.Property<long>("PatioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.DeteccaoVisual", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CameraId")
                        .HasColumnType("bigint");

                    b.Property<double>("Confianca")
                        .HasColumnType("float");

                    b.Property<string>("ImagemCaptura")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("MotoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("MotoId");

                    b.ToTable("DeteccoesVisuais");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.EventoMoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CameraId")
                        .HasColumnType("bigint");

                    b.Property<string>("FonteEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("MotoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("SensorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("MotoId");

                    b.HasIndex("SensorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.LocalizacaoMoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Confiabilidade")
                        .HasColumnType("float");

                    b.Property<string>("FonteDados")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("MotoId")
                        .HasColumnType("bigint");

                    b.Property<long>("PatioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MotoId");

                    b.HasIndex("PatioId");

                    b.ToTable("Localizacoes");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.Moto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("CaracteristicasVisuais")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("ImagemReferencia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("PatioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RFIDTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UltimaManutencao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("Motos");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.Patio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlantaBaixa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Patios");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.SensorRFID", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<double>("AnguloVisao")
                        .HasColumnType("float");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<long>("PatioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UltimaLeitura")
                        .HasColumnType("datetime2");

                    b.Property<long>("ZonaPatioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.HasIndex("ZonaPatioId");

                    b.ToTable("SensorRFID", (string)null);
                });

            modelBuilder.Entity("Trackin.Domain.Entity.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("PatioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Senha");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.ZonaPatio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("PatioId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoZona")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("ZonasPatio");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.Camera", b =>
                {
                    b.HasOne("Trackin.Domain.Entity.Patio", "Patio")
                        .WithMany("Cameras")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Trackin.Domain.ValueObjects.Coordenada", "PosicaoPatio", b1 =>
                        {
                            b1.Property<long>("CameraId")
                                .HasColumnType("bigint");

                            b1.Property<double>("X")
                                .HasColumnType("float")
                                .HasColumnName("PosicaoX");

                            b1.Property<double>("Y")
                                .HasColumnType("float")
                                .HasColumnName("PosicaoY");

                            b1.HasKey("CameraId");

                            b1.ToTable("Cameras");

                            b1.WithOwner()
                                .HasForeignKey("CameraId");
                        });

                    b.Navigation("Patio");

                    b.Navigation("PosicaoPatio")
                        .IsRequired();
                });

            modelBuilder.Entity("Trackin.Domain.Entity.DeteccaoVisual", b =>
                {
                    b.HasOne("Trackin.Domain.Entity.Camera", "Camera")
                        .WithMany("DeteccoesVisuais")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trackin.Domain.Entity.Moto", "Moto")
                        .WithMany("DeteccoesVisuais")
                        .HasForeignKey("MotoId");

                    b.OwnsOne("Trackin.Domain.ValueObjects.Coordenada", "PosicaoImagem", b1 =>
                        {
                            b1.Property<long>("DeteccaoVisualId")
                                .HasColumnType("bigint");

                            b1.Property<double>("X")
                                .HasColumnType("float")
                                .HasColumnName("CoordenadaXImagem");

                            b1.Property<double>("Y")
                                .HasColumnType("float")
                                .HasColumnName("CoordenadaYImagem");

                            b1.HasKey("DeteccaoVisualId");

                            b1.ToTable("DeteccoesVisuais");

                            b1.WithOwner()
                                .HasForeignKey("DeteccaoVisualId");
                        });

                    b.OwnsOne("Trackin.Domain.ValueObjects.Coordenada", "PosicaoPatio", b1 =>
                        {
                            b1.Property<long>("DeteccaoVisualId")
                                .HasColumnType("bigint");

                            b1.Property<double>("X")
                                .HasColumnType("float")
                                .HasColumnName("CoordenadaXPatio");

                            b1.Property<double>("Y")
                                .HasColumnType("float")
                                .HasColumnName("CoordenadaYPatio");

                            b1.HasKey("DeteccaoVisualId");

                            b1.ToTable("DeteccoesVisuais");

                            b1.WithOwner()
                                .HasForeignKey("DeteccaoVisualId");
                        });

                    b.Navigation("Camera");

                    b.Navigation("Moto");

                    b.Navigation("PosicaoImagem")
                        .IsRequired();

                    b.Navigation("PosicaoPatio")
                        .IsRequired();
                });

            modelBuilder.Entity("Trackin.Domain.Entity.EventoMoto", b =>
                {
                    b.HasOne("Trackin.Domain.Entity.Camera", "Camera")
                        .WithMany("Eventos")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Trackin.Domain.Entity.Moto", "Moto")
                        .WithMany("Eventos")
                        .HasForeignKey("MotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trackin.Domain.Entity.SensorRFID", "Sensor")
                        .WithMany("Eventos")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Trackin.Domain.Entity.Usuario", "Usuario")
                        .WithMany("Eventos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Camera");

                    b.Navigation("Moto");

                    b.Navigation("Sensor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.LocalizacaoMoto", b =>
                {
                    b.HasOne("Trackin.Domain.Entity.Moto", "Moto")
                        .WithMany("Localizacoes")
                        .HasForeignKey("MotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trackin.Domain.Entity.Patio", "Patio")
                        .WithMany("Localizacoes")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Trackin.Domain.ValueObjects.Coordenada", "Posicao", b1 =>
                        {
                            b1.Property<long>("LocalizacaoMotoId")
                                .HasColumnType("bigint");

                            b1.Property<double>("X")
                                .HasColumnType("float")
                                .HasColumnName("CoordenadaX");

                            b1.Property<double>("Y")
                                .HasColumnType("float")
                                .HasColumnName("CoordenadaY");

                            b1.HasKey("LocalizacaoMotoId");

                            b1.ToTable("Localizacoes");

                            b1.WithOwner()
                                .HasForeignKey("LocalizacaoMotoId");
                        });

                    b.Navigation("Moto");

                    b.Navigation("Patio");

                    b.Navigation("Posicao")
                        .IsRequired();
                });

            modelBuilder.Entity("Trackin.Domain.Entity.Moto", b =>
                {
                    b.HasOne("Trackin.Domain.Entity.Patio", "Patio")
                        .WithMany()
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.Patio", b =>
                {
                    b.OwnsOne("Trackin.Domain.ValueObjects.Coordenada", "Dimensoes", b1 =>
                        {
                            b1.Property<long>("PatioId")
                                .HasColumnType("bigint");

                            b1.Property<double>("X")
                                .HasColumnType("float")
                                .HasColumnName("DimensaoX");

                            b1.Property<double>("Y")
                                .HasColumnType("float")
                                .HasColumnName("DimensaoY");

                            b1.HasKey("PatioId");

                            b1.ToTable("Patios");

                            b1.WithOwner()
                                .HasForeignKey("PatioId");
                        });

                    b.Navigation("Dimensoes")
                        .IsRequired();
                });

            modelBuilder.Entity("Trackin.Domain.Entity.SensorRFID", b =>
                {
                    b.HasOne("Trackin.Domain.Entity.Patio", "Patio")
                        .WithMany("SensoresRFID")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trackin.Domain.Entity.ZonaPatio", "ZonaPatio")
                        .WithMany("SensoresRFID")
                        .HasForeignKey("ZonaPatioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Trackin.Domain.ValueObjects.Coordenada", "PosicaoSensor", b1 =>
                        {
                            b1.Property<long>("SensorRFIDId")
                                .HasColumnType("bigint");

                            b1.Property<double>("X")
                                .HasColumnType("float")
                                .HasColumnName("PosicaoX");

                            b1.Property<double>("Y")
                                .HasColumnType("float")
                                .HasColumnName("PosicaoY");

                            b1.HasKey("SensorRFIDId");

                            b1.ToTable("SensorRFID");

                            b1.WithOwner()
                                .HasForeignKey("SensorRFIDId");
                        });

                    b.Navigation("Patio");

                    b.Navigation("PosicaoSensor")
                        .IsRequired();

                    b.Navigation("ZonaPatio");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.Usuario", b =>
                {
                    b.HasOne("Trackin.Domain.Entity.Patio", "Patio")
                        .WithMany("Usuarios")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.ZonaPatio", b =>
                {
                    b.HasOne("Trackin.Domain.Entity.Patio", "Patio")
                        .WithMany("Zonas")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Trackin.Domain.ValueObjects.Coordenada", "PontoFinal", b1 =>
                        {
                            b1.Property<long>("ZonaPatioId")
                                .HasColumnType("bigint");

                            b1.Property<double>("X")
                                .HasColumnType("float")
                                .HasColumnName("CoordenadaFinalX");

                            b1.Property<double>("Y")
                                .HasColumnType("float")
                                .HasColumnName("CoordenadaFinalY");

                            b1.HasKey("ZonaPatioId");

                            b1.ToTable("ZonasPatio");

                            b1.WithOwner()
                                .HasForeignKey("ZonaPatioId");
                        });

                    b.OwnsOne("Trackin.Domain.ValueObjects.Coordenada", "PontoInicial", b1 =>
                        {
                            b1.Property<long>("ZonaPatioId")
                                .HasColumnType("bigint");

                            b1.Property<double>("X")
                                .HasColumnType("float")
                                .HasColumnName("CoordenadaInicialX");

                            b1.Property<double>("Y")
                                .HasColumnType("float")
                                .HasColumnName("CoordenadaInicialY");

                            b1.HasKey("ZonaPatioId");

                            b1.ToTable("ZonasPatio");

                            b1.WithOwner()
                                .HasForeignKey("ZonaPatioId");
                        });

                    b.Navigation("Patio");

                    b.Navigation("PontoFinal")
                        .IsRequired();

                    b.Navigation("PontoInicial")
                        .IsRequired();
                });

            modelBuilder.Entity("Trackin.Domain.Entity.Camera", b =>
                {
                    b.Navigation("DeteccoesVisuais");

                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.Moto", b =>
                {
                    b.Navigation("DeteccoesVisuais");

                    b.Navigation("Eventos");

                    b.Navigation("Localizacoes");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.Patio", b =>
                {
                    b.Navigation("Cameras");

                    b.Navigation("Localizacoes");

                    b.Navigation("SensoresRFID");

                    b.Navigation("Usuarios");

                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.SensorRFID", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.Usuario", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Trackin.Domain.Entity.ZonaPatio", b =>
                {
                    b.Navigation("SensoresRFID");
                });
#pragma warning restore 612, 618
        }
    }
}
