// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Trackin.Infrastructure.Context;

#nullable disable

namespace Trackin.API.Migrations
{
    [DbContext(typeof(TrackinContext))]
    [Migration("20250429220005_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trackin.API.Domain.Entity.Camera", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("AnguloVisao")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<long>("PatioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("PatioId1")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<double>("PosicaoX")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("PosicaoY")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.HasIndex("PatioId1");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.DeteccaoVisual", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CameraId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<double>("Confianca")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("CoordenadaXImagem")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("CoordenadaXPatio")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("CoordenadaYImagem")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("CoordenadaYPatio")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("ImagemCaptura")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<long?>("MotoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("MotoId");

                    b.ToTable("DeteccoesVisuais");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.EventoMoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CameraId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("FonteEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<long>("MotoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<long?>("SensorId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("MotoId");

                    b.HasIndex("SensorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.LocalizacaoMoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Confiabilidade")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("CoordenadaX")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("CoordenadaY")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("FonteDados")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<long>("MotoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("PatioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("MotoId");

                    b.HasIndex("PatioId");

                    b.ToTable("Localizacoes");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.Moto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CaracteristicasVisuais")
                        .HasColumnType("CLOB");

                    b.Property<string>("ImagemReferencia")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<long>("PatioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("RFIDTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<DateTime?>("UltimaManutencao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("Motos");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.Patio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<double>("DimensaoX")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("DimensaoY")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("PlantaBaixa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("Id");

                    b.ToTable("Patios");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.SensorRFID", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("AnguloVisao")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<long>("PatioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<double>("PosicaoX")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("PosicaoY")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<long>("ZonaPatioId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.HasIndex("ZonaPatioId");

                    b.ToTable("SensorRFID", (string)null);
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<long>("PatioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.ZonaPatio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CoordenadaFinalX")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("CoordenadaFinalY")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("CoordenadaInicialX")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("CoordenadaInicialY")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<long>("PatioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("TipoZona")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("ZonasPatio");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.Camera", b =>
                {
                    b.HasOne("Trackin.API.Domain.Entity.Patio", "Patio")
                        .WithMany("Camera")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trackin.API.Domain.Entity.Patio", null)
                        .WithMany("Cameras")
                        .HasForeignKey("PatioId1");

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.DeteccaoVisual", b =>
                {
                    b.HasOne("Trackin.API.Domain.Entity.Camera", "Camera")
                        .WithMany("DeteccoesVisuais")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trackin.API.Domain.Entity.Moto", "Moto")
                        .WithMany("DeteccoesVisuais")
                        .HasForeignKey("MotoId");

                    b.Navigation("Camera");

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.EventoMoto", b =>
                {
                    b.HasOne("Trackin.API.Domain.Entity.Camera", "Camera")
                        .WithMany("Eventos")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Trackin.API.Domain.Entity.Moto", "Moto")
                        .WithMany("Eventos")
                        .HasForeignKey("MotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trackin.API.Domain.Entity.SensorRFID", "Sensor")
                        .WithMany("Eventos")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Trackin.API.Domain.Entity.Usuario", "Usuario")
                        .WithMany("Eventos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Camera");

                    b.Navigation("Moto");

                    b.Navigation("Sensor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.LocalizacaoMoto", b =>
                {
                    b.HasOne("Trackin.API.Domain.Entity.Moto", "Moto")
                        .WithMany("Localizacoes")
                        .HasForeignKey("MotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trackin.API.Domain.Entity.Patio", "Patio")
                        .WithMany("Localizacoes")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moto");

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.Moto", b =>
                {
                    b.HasOne("Trackin.API.Domain.Entity.Patio", "Patio")
                        .WithMany()
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.SensorRFID", b =>
                {
                    b.HasOne("Trackin.API.Domain.Entity.Patio", "Patio")
                        .WithMany("SensoresRFID")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trackin.API.Domain.Entity.ZonaPatio", "ZonaPatio")
                        .WithMany("SensoresRFID")
                        .HasForeignKey("ZonaPatioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patio");

                    b.Navigation("ZonaPatio");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.Usuario", b =>
                {
                    b.HasOne("Trackin.API.Domain.Entity.Patio", "Patio")
                        .WithMany("Usuarios")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.ZonaPatio", b =>
                {
                    b.HasOne("Trackin.API.Domain.Entity.Patio", "Patio")
                        .WithMany("Zonas")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.Camera", b =>
                {
                    b.Navigation("DeteccoesVisuais");

                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.Moto", b =>
                {
                    b.Navigation("DeteccoesVisuais");

                    b.Navigation("Eventos");

                    b.Navigation("Localizacoes");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.Patio", b =>
                {
                    b.Navigation("Camera");

                    b.Navigation("Cameras");

                    b.Navigation("Localizacoes");

                    b.Navigation("SensoresRFID");

                    b.Navigation("Usuarios");

                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.SensorRFID", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.Usuario", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Trackin.API.Domain.Entity.ZonaPatio", b =>
                {
                    b.Navigation("SensoresRFID");
                });
#pragma warning restore 612, 618
        }
    }
}
